# arg 1:  the new package version
post_install() {
  echo -n "updating font cache... "
  sbin/ldconfig -r .
  usr/bin/fc-cache
  cd usr/X11R6/lib/X11/fonts/TTF
  ../../../../bin/mkfontscale
  ../../../../bin/mkfontdir
  cp ../encodings/encodings.dir ./encodings.dir 
  echo "done."
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
