post_install() {
	# we need to ldconfig first, in case X libs aren't
	# in ld.so.cache yet
	sbin/ldconfig -r .
	mkdir -p etc/gtk-2.0 &>/dev/null
	usr/bin/gtk-query-immodules-2.0 >etc/gtk-2.0/gtk.immodules
	usr/bin/gdk-pixbuf-query-loaders >etc/gtk-2.0/gdk-pixbuf.loaders
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	rm -f etc/gtk-2.0/gtk.immodules &>/dev/null
	rmdir etc/gtk-2.0 &>/dev/null
}

op=$1
shift

$op $*
